### ISSUE TITLE
More built-in OpenTelemetry instrumentations

### ISSUE THREAD

**Issue by dahlia** [fedify-dev/fedify#170]
Curently, there's only one built-in instrumentation in Fedify.  It would be great if we have more built-in instrumentations, such as:

- [x] parsing a request into a Fedify Activity instance
- [x] object dispatchers
- [x] sending an activity (after reading off the queue)
- [x] sending an activity (time from `sendActivity()` to objects on the queue)
- [x] collection/collectionpage dispatchers
- [x] async methods of activities/objects (maybe this is at docloader level?)

**Comment by Heesunni** [comment]
도전해보겠습니닷
